### ISSUE TITLE
jaxws-maven-plugin 2.3.1-b03 doesn't work with Maven >= 3.1.x

### ISSUE THREAD

**Issue by glassfishrobot** [javaee/metro-jaxws-commons#127]
The modifications in #108 don't work anymore with Maven >= 3.1.x because Sonatype Aether was replaced with Eclipse aether. See also

*   [http://wiki.eclipse.org/Aether/Using_Aether_in_Maven_Plugins](http://wiki.eclipse.org/Aether/Using_Aether_in_Maven_Plugins)
*   [http://www.sonatype.org/aether](http://www.sonatype.org/aether)

The actual result is a NoClassDefFoundError when I use org.jvnet.jax-ws-commons:jaxws-maven-plugin:2.3.1-b03 (available at Maven Central repository) in combination with the recently released Maven 3.2.1:

```
$ mvn clean package
[INFO] Scanning for projects...
[INFO] 
[INFO] Using the builder org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder with a thread count of 1
[INFO]         
[INFO] ------------------------------------------------------------------------
[INFO] Building myproject-common 2014.1.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ myproject-common ---
[INFO] Deleting /home/thorsten/workspaces/myproject-common/target
[INFO] 
[INFO] --- jaxws-maven-plugin:2.3.1-b03:wsimport (default) @ myproject-common ---
[WARNING] Error injecting: org.jvnet.jax_ws_commons.jaxws.MainWsImportMojo
java.lang.NoClassDefFoundError: org/sonatype/aether/resolution/DependencyResolutionException
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2658)
	at java.lang.Class.getDeclaredConstructors(Class.java:2007)
	at com.google.inject.spi.InjectionPoint.forConstructorOf(InjectionPoint.java:245)
	at com.google.inject.internal.ConstructorBindingImpl.create(ConstructorBindingImpl.java:99)
(...)
Caused by: java.lang.ClassNotFoundException: org.sonatype.aether.resolution.DependencyResolutionException
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:259)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:235)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:227)
	... 54 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.471 s
[INFO] Finished at: 2014-03-17T11:57:49+01:00
[INFO] Final Memory: 9M/818M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.jvnet.jax-ws-commons:jaxws-maven-plugin:2.3.1-b03:wsimport (default) on project myproject-common: Execution default of goal org.jvnet.jax-ws-commons:jaxws-maven-plugin:2.3.1-b03:wsimport failed: A required class was missing while executing org.jvnet.jax-ws-commons:jaxws-maven-plugin:2.3.1-b03:wsimport: org/sonatype/aether/resolution/DependencyResolutionException
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.jvnet.jax-ws-commons:jaxws-maven-plugin:2.3.1-b03
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
(...)
```
```
**pom.xml**<plugin>
  <groupId>org.jvnet.jax-ws-commons</groupId>
  <artifactId>jaxws-maven-plugin</artifactId>
  <version>2.3.1-b03</version>
  <executions>
    <execution>
      <goals>
        <goal>wsimport</goal>
      </goals>
      <configuration>
        <wsdlDirectory>${basedir}/src/main/resources/wsdl</wsdlDirectory>
        <wsdlFiles>
          <wsdlFile>mywsdl.wsdl</wsdlFile>
        </wsdlFiles>
        <target>2.1</target>
        <wsdlLocation>/wsdl/mywsdl.wsdl</wsdlLocation>
      </configuration>
    </execution>
  </executions>
</plugin>
```

However, plugin versions 2.3 or older work.
#### Environment
Maven 3.2.1
Java 7u51, Java 8 b132
Solaris 11.1 x86_64
#### Affected Versions
[2.3.1]
